@startuml
set namespaceSeparator ::

class "amcham_app_v2::size_config.dart::SizeConfig" {
  {static} -MediaQueryData _mediaQueryData
  {static} +double screenWidth
  {static} +double screenHeight
  {static} +double blockSizeHorizontal
  {static} +double blockSizeVertical
  {static} -double _safeAreaHorizontal
  {static} -double _safeAreaVertical
  {static} +double safeBlockHorizontal
  {static} +double safeBlockVertical
  +double getScreenHeight()
  +double getScreenWidth()
  +double getBlockSizeVertical()
  +double getBlockSizeHorizontal()
  +void init()
}

"amcham_app_v2::size_config.dart::SizeConfig" o-- "flutter::src::widgets::media_query.dart::MediaQueryData"

class "amcham_app_v2::push_nofitications.dart::PushNotificationsManager" {
  {static} -PushNotificationsManager _instance
  -FirebaseMessaging _firebaseMessaging
  -bool _initialized
  +dynamic init()
}

"amcham_app_v2::push_nofitications.dart::PushNotificationsManager" o-- "amcham_app_v2::push_nofitications.dart::PushNotificationsManager"
"amcham_app_v2::push_nofitications.dart::PushNotificationsManager" o-- "firebase_messaging::firebase_messaging.dart::FirebaseMessaging"

class "amcham_app_v2::screens::events_screen.dart::EventsScreen" {
  +_EventsScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::events_screen.dart::EventsScreen"

class "amcham_app_v2::screens::events_screen.dart::_EventsScreenState" {
  -int _selectedIndex
  +Container eventItems
  +bool isPastEvents
  +bool isMyEvents
  +bool isSearching
  +List<int> searchHash
  +MemberChecker memberChecker
  -void _onItemTapped()
  +void getData()
  +void initState()
  +dynamic getIfMember()
  +dynamic printMember()
  +List seperateWords()
  +void search()
  +void clearSearch()
  +Widget build()
}

"amcham_app_v2::screens::events_screen.dart::_EventsScreenState" o-- "flutter::src::widgets::container.dart::Container"
"amcham_app_v2::screens::events_screen.dart::_EventsScreenState" o-- "amcham_app_v2::scripts::member_checker.dart::MemberChecker"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::events_screen.dart::_EventsScreenState"

class "amcham_app_v2::screens::events_screen.dart::EventsStream" {
  +CollectionReference eventsRef
  +bool isPastEvents
  +bool isMyEvents
  +bool isSearching
  +List<int> searchHash
  +EventItem getItem()
  +bool getIfMyEvent()
  +Widget build()
}

"amcham_app_v2::screens::events_screen.dart::EventsStream" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::events_screen.dart::EventsStream"

class "amcham_app_v2::screens::single_event_screen.dart::SingleEventScreen" {
  +dynamic testStr
  +EventItem item
  +dynamic DateToString()
  +_SingleEventScreenState createState()
}

"amcham_app_v2::screens::single_event_screen.dart::SingleEventScreen" o-- "amcham_app_v2::components::event_item.dart::EventItem"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::single_event_screen.dart::SingleEventScreen"

class "amcham_app_v2::screens::single_event_screen.dart::_SingleEventScreenState" {
  +BoxDecoration activeDecoration
  +BoxDecoration inActiveDecoration
  +bool isInfoActive
  +EventItem item
  +dynamic userEmail
  +SpeakersList speakersList
  +void initState()
  +bool checkOwnedEvent()
  +Widget build()
}

"amcham_app_v2::screens::single_event_screen.dart::_SingleEventScreenState" o-- "flutter::src::painting::box_decoration.dart::BoxDecoration"
"amcham_app_v2::screens::single_event_screen.dart::_SingleEventScreenState" o-- "amcham_app_v2::components::event_item.dart::EventItem"
"amcham_app_v2::screens::single_event_screen.dart::_SingleEventScreenState" o-- "amcham_app_v2::screens::single_event_screen.dart::SpeakersList"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::single_event_screen.dart::_SingleEventScreenState"

class "amcham_app_v2::screens::single_event_screen.dart::SpeakersList" {
  +List speakers
  +List<SpeakerItem> speakerItemList
  +void generateSpeakers()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::single_event_screen.dart::SpeakersList"

class "amcham_app_v2::screens::single_event_screen.dart::SpeakerItem" {
  +dynamic title
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::single_event_screen.dart::SpeakerItem"

class "amcham_app_v2::screens::verify_screen.dart::VerifyScreen" {
  +_VerifyScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::verify_screen.dart::VerifyScreen"

class "amcham_app_v2::screens::verify_screen.dart::_VerifyScreenState" {
  +FirebaseAuth auth
  +User user
  {static} +Timer timer
  +bool isResendLoading
  +void initState()
  -dynamic _alertDialogBuilder()
  +void dispose()
  +void sendMail()
  +dynamic checkEmailVerified()
  +Widget build()
}

"amcham_app_v2::screens::verify_screen.dart::_VerifyScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"amcham_app_v2::screens::verify_screen.dart::_VerifyScreenState" o-- "firebase_auth::firebase_auth.dart::User"
"amcham_app_v2::screens::verify_screen.dart::_VerifyScreenState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::verify_screen.dart::_VerifyScreenState"

class "amcham_app_v2::screens::news_screen.dart::UpdatesScreen" {
  +_UpdatesScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::news_screen.dart::UpdatesScreen"

class "amcham_app_v2::screens::news_screen.dart::_UpdatesScreenState" {
  +void initState()
  +void search()
  +void clearSearch()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::news_screen.dart::_UpdatesScreenState"

class "amcham_app_v2::screens::news_screen.dart::NewsStream" {
  +CollectionReference newsRef
  +bool isSearching
  +List<int> searchHash
  +NewsItem getItem()
  +bool getIfMyEvent()
  +Widget build()
}

"amcham_app_v2::screens::news_screen.dart::NewsStream" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::news_screen.dart::NewsStream"

class "amcham_app_v2::screens::single_news_screen.dart::SingleNewsScreen" {
  +dynamic testStr
  +NewsItem item
  +dynamic DateToString()
  +_SingleNewsScreenState createState()
}

"amcham_app_v2::screens::single_news_screen.dart::SingleNewsScreen" o-- "amcham_app_v2::components::news_item.dart::NewsItem"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::single_news_screen.dart::SingleNewsScreen"

class "amcham_app_v2::screens::single_news_screen.dart::_SingleNewsScreenState" {
  +BoxDecoration activeDecoration
  +BoxDecoration inActiveDecoration
  +bool isInfoActive
  +bool isLinkActive
  +NewsItem item
  +dynamic url
  +dynamic userEmail
  +void initState()
  -dynamic _launchURL()
  +Widget build()
}

"amcham_app_v2::screens::single_news_screen.dart::_SingleNewsScreenState" o-- "flutter::src::painting::box_decoration.dart::BoxDecoration"
"amcham_app_v2::screens::single_news_screen.dart::_SingleNewsScreenState" o-- "amcham_app_v2::components::news_item.dart::NewsItem"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::single_news_screen.dart::_SingleNewsScreenState"

class "amcham_app_v2::screens::profile_screen.dart::ProfileScreen" {
  +_ProfileScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::profile_screen.dart::ProfileScreen"

class "amcham_app_v2::screens::profile_screen.dart::_ProfileScreenState" {
  -FirebaseAuth _firebaseAuth
  +dynamic email
  +dynamic firstName
  +dynamic lastName
  +dynamic company
  +bool isInfoLoading
  +bool isPasswordLoading
  +MemberChecker memberChecker
  +CollectionReference users
  -dynamic _alertDialogBuilder()
  +void initState()
  +dynamic getIfMember()
  +dynamic updateUserInfo()
  +void getInfo()
  +Widget build()
}

"amcham_app_v2::screens::profile_screen.dart::_ProfileScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"amcham_app_v2::screens::profile_screen.dart::_ProfileScreenState" o-- "amcham_app_v2::scripts::member_checker.dart::MemberChecker"
"amcham_app_v2::screens::profile_screen.dart::_ProfileScreenState" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::profile_screen.dart::_ProfileScreenState"

class "amcham_app_v2::screens::profile_screen.dart::dataInput" {
  +dynamic title
  +dynamic data
  +dynamic Function(dynamic) onChanged
  +Widget build()
}

"amcham_app_v2::screens::profile_screen.dart::dataInput" o-- "amcham_app_v2::screens::profile_screen.dart::dynamic Function(dynamic)"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::profile_screen.dart::dataInput"

class "amcham_app_v2::screens::register_screen.dart::RegisterScreen" {
  +_RegisterScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::register_screen.dart::RegisterScreen"

class "amcham_app_v2::screens::register_screen.dart::_RegisterScreenState" {
  +FirebaseFirestore firestore
  +CollectionReference users
  +bool isLoading
  -dynamic _firstName
  -dynamic _lastName
  -dynamic _email
  -dynamic _password
  -dynamic _passwordConf
  -dynamic _company
  -FocusNode _lastNameFocusNode
  -FocusNode _companyFocusNode
  -FocusNode _emailFocusNode
  -FocusNode _passwordFocusNode
  -FocusNode _passwordConfFocusNode
  -dynamic _alertDialogBuilder()
  +dynamic addUserInfo()
  -dynamic _createAccount()
  -void _submitForm()
  +void initState()
  +void dispose()
  +bool validateFields()
  +Widget build()
}

"amcham_app_v2::screens::register_screen.dart::_RegisterScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"amcham_app_v2::screens::register_screen.dart::_RegisterScreenState" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference"
"amcham_app_v2::screens::register_screen.dart::_RegisterScreenState" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::register_screen.dart::_RegisterScreenState"

class "amcham_app_v2::screens::login_screen.dart::LoginScreen" {
  +_LoginScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::login_screen.dart::LoginScreen"

class "amcham_app_v2::screens::login_screen.dart::_LoginScreenState" {
  +bool isLoading
  -dynamic _email
  -dynamic _password
  -FocusNode _lastNameFocusNode
  -FocusNode _companyFocusNode
  -FocusNode _emailFocusNode
  -FocusNode _passwordFocusNode
  -FocusNode _passwordConfFocusNode
  -dynamic _alertDialogBuilder()
  -dynamic _loginToAccount()
  -void _submitForm()
  +void initState()
  +void dispose()
  +Widget build()
}

"amcham_app_v2::screens::login_screen.dart::_LoginScreenState" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::login_screen.dart::_LoginScreenState"

class "amcham_app_v2::screens::forgot_password_screen.dart::ForgotPasswordScreen" {
  +_ForgotPasswordScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::forgot_password_screen.dart::ForgotPasswordScreen"

class "amcham_app_v2::screens::forgot_password_screen.dart::_ForgotPasswordScreenState" {
  -FirebaseAuth _firebaseAuth
  +bool isResetPasswordLoading
  -dynamic _email
  -dynamic _alertDialogBuilder()
  +Widget build()
}

"amcham_app_v2::screens::forgot_password_screen.dart::_ForgotPasswordScreenState" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::forgot_password_screen.dart::_ForgotPasswordScreenState"

class "amcham_app_v2::screens::landing_page.dart::LandingPage" {
  -dynamic _initialization
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::landing_page.dart::LandingPage"

class "amcham_app_v2::screens::home_page.dart::HomePage" {
  +_HomePageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::home_page.dart::HomePage"

class "amcham_app_v2::screens::home_page.dart::_HomePageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::home_page.dart::_HomePageState"

class "amcham_app_v2::screens::development_screen.dart::DevelopmentScreen" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::screens::development_screen.dart::DevelopmentScreen"

class "amcham_app_v2::screens::event_register_screen.dart::EventRegisterScreen" {
  +EventItem eventItem
  +dynamic id
  +bool isEventAlreadyOwned
  +_EventRegisterScreenState createState()
}

"amcham_app_v2::screens::event_register_screen.dart::EventRegisterScreen" o-- "amcham_app_v2::components::event_item.dart::EventItem"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::event_register_screen.dart::EventRegisterScreen"

class "amcham_app_v2::screens::event_register_screen.dart::_EventRegisterScreenState" {
  +FirebaseFirestore firestore
  +EventItem eventItem
  +dynamic id
  +bool isEventAlreadyOwned
  +bool isTopLoading
  +bool isBottomLoading
  +CollectionReference userInfo
  +CollectionReference eventsInfo
  +dynamic userEmail
  +bool isThereDuplicate()
  +dynamic updateUser()
  +dynamic updateEvent()
  +dynamic sendEmail()
  +void addToCalendar()
  +DateTime getDateFromItem()
  +void initState()
  -dynamic _alertDialogBuilder()
  +Widget build()
}

"amcham_app_v2::screens::event_register_screen.dart::_EventRegisterScreenState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"amcham_app_v2::screens::event_register_screen.dart::_EventRegisterScreenState" o-- "amcham_app_v2::components::event_item.dart::EventItem"
"amcham_app_v2::screens::event_register_screen.dart::_EventRegisterScreenState" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference"
"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::event_register_screen.dart::_EventRegisterScreenState"

class "amcham_app_v2::screens::feedback_screen.dart::FeedbackScreen" {
  +_FeedbackScreenState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::screens::feedback_screen.dart::FeedbackScreen"

class "amcham_app_v2::screens::feedback_screen.dart::_FeedbackScreenState" {
  +bool isBug
  +dynamic message
  +bool isLoading
  +dynamic submit()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::screens::feedback_screen.dart::_FeedbackScreenState"

class "amcham_app_v2::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::main.dart::MyApp"

class "amcham_app_v2::hash_table.dart::HashTable" {
}

class "amcham_app_v2::components::forgot_password.dart::ForgotPassword" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::forgot_password.dart::ForgotPassword"

class "amcham_app_v2::components::event_item.dart::EventItem" {
  +MemberChecker memberChecker
  +int price
  +int date
  +int startTime
  +int endTime
  +dynamic title
  +dynamic type
  +dynamic category
  +bool isMembersOnly
  +dynamic summary
  +dynamic imageRef
  +dynamic info
  +dynamic id
  +dynamic link
  +List registeredUsers
  +List tier1hashes
  +List tier2hashes
  +List tier3hashes
  +List tier4hashes
  +List speakers
  +bool isButton
  +bool showInfo
  +bool hideSummary
  +bool isInfoSelected
  +Function infoButtonFunction
  +Function speakersButtonFunction
  +int rankedPoints
  +int getPointsFromHashes()
  +dynamic DateToString()
  +dynamic TimeToString()
  +Widget build()
}

"amcham_app_v2::components::event_item.dart::EventItem" o-- "amcham_app_v2::scripts::member_checker.dart::MemberChecker"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::event_item.dart::EventItem"

class "amcham_app_v2::components::alert_dialog_builder.dart::FeedbackBuilder" {
  {static} +dynamic alertDialogBuilder()
}

class "amcham_app_v2::components::rounded_button.dart::RoundedButton" {
  +Color colour
  +dynamic title
  +Function onPressed
  +double radius
  +TextStyle textStyle
  +double height
  +double width
  +bool isLoading
  +dynamic boxDecoration
  +Widget build()
}

"amcham_app_v2::components::rounded_button.dart::RoundedButton" o-- "dart::ui::Color"
"amcham_app_v2::components::rounded_button.dart::RoundedButton" o-- "flutter::src::painting::text_style.dart::TextStyle"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::rounded_button.dart::RoundedButton"

class "amcham_app_v2::components::get_firebase_image.dart::LoadFirebaseStorageImage" {
  +FirebaseStorage storage
  +dynamic imageRef
  +Widget build()
  -dynamic _getImage()
}

"amcham_app_v2::components::get_firebase_image.dart::LoadFirebaseStorageImage" o-- "firebase_storage::firebase_storage.dart::FirebaseStorage"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::get_firebase_image.dart::LoadFirebaseStorageImage"

class "amcham_app_v2::components::news_item.dart::NewsItem" {
  +int dateTime
  +dynamic summaryText
  +dynamic imageRef
  +dynamic info
  +dynamic id
  +List tier1hashes
  +List tier2hashes
  +List tier3hashes
  +dynamic title
  +dynamic link
  +bool isButton
  +bool showInfo
  +bool hideSummary
  +bool isInfoSelected
  +Function infoButtonFunction
  +Function speakersButtonFunction
  +bool enableImage
  +int rankedPoints
  +int getPointsFromHashes()
  +dynamic DateToString()
  +dynamic TimeToString()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::news_item.dart::NewsItem"

class "amcham_app_v2::components::bottom_bar.dart::BottomBar" {
  +bool isEventsScreen
  +bool getIsEventsScreen()
  +_BottomBarState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "amcham_app_v2::components::bottom_bar.dart::BottomBar"

class "amcham_app_v2::components::bottom_bar.dart::_BottomBarState" {
  +bool isEventsScreen
  {static} +bool isButton1Active
  {static} +bool isButton2Active
  {static} +bool isButton3Active
  +void SetDefault()
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "amcham_app_v2::components::bottom_bar.dart::_BottomBarState"

class "amcham_app_v2::components::amcham_logo.dart::AmchamLogo" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::amcham_logo.dart::AmchamLogo"

class "amcham_app_v2::components::search_app_bar.dart::SearchAppbar" {
  +dynamic Function(dynamic) searchFunction
  +Function clearFunction
  +dynamic searchString
  +bool isSearching
  +dynamic getSearchString()
  +void setSearchString()
  +Widget build()
}

"amcham_app_v2::components::search_app_bar.dart::SearchAppbar" o-- "amcham_app_v2::components::search_app_bar.dart::dynamic Function(dynamic)"
"flutter::src::widgets::preferred_size.dart::PreferredSize" <|-- "amcham_app_v2::components::search_app_bar.dart::SearchAppbar"

class "amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" {
  +Color colour
  +dynamic title
  +double radius
  +TextStyle textStyle
  +double height
  +double width
  +dynamic hintText
  +dynamic Function(dynamic) onChanged
  +dynamic Function(dynamic) onSubmitted
  +FocusNode focusNode
  +TextInputAction textInputAction
  +bool isPasswordField
  +dynamic textValue
  +double shadowOpacity
  +BoxBorder border
  +Widget build()
}

"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "dart::ui::Color"
"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "flutter::src::painting::text_style.dart::TextStyle"
"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "amcham_app_v2::components::rounded_text_field.dart::dynamic Function(dynamic)"
"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "flutter::src::widgets::focus_manager.dart::FocusNode"
"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "flutter::src::services::text_input.dart::TextInputAction"
"amcham_app_v2::components::rounded_text_field.dart::RoundedTextField" o-- "flutter::src::painting::box_border.dart::BoxBorder"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "amcham_app_v2::components::rounded_text_field.dart::RoundedTextField"

class "amcham_app_v2::scripts::member_checker.dart::MemberChecker" {
  +FirebaseFirestore firestore
  +dynamic userEmail
  {static} +bool isMember
  {static} +List emailEndings
  +void main()
  +bool checkIfMember()
  +dynamic updateEndings()
}

"amcham_app_v2::scripts::member_checker.dart::MemberChecker" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"

class "amcham_app_v2::constants.dart::Constants" {
  {static} +int num
  {static} +TextStyle regularHeading
  {static} +TextStyle logoTitleStyle
  {static} +TextStyle whiteTextStyle
  {static} +TextStyle logoTitleStyleRed
  {static} +Color blueThemeColor
  {static} +Color darkBlueThemeColor
  {static} +TextStyle blueText
}

"amcham_app_v2::constants.dart::Constants" o-- "flutter::src::painting::text_style.dart::TextStyle"
"amcham_app_v2::constants.dart::Constants" o-- "dart::ui::Color"


@enduml